# Generated by Django 2.0 on 2018-01-03 04:56

from django.db import migrations, models
import django.db.models.deletion
import mhc.storage_backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='HH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=mhc.storage_backend.PrivateUnconvertedStorage(), upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HH_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.HH')),
            ],
        ),
        migrations.CreateModel(
            name='HH_Player_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('count', models.IntegerField(default=0)),
                ('sit', models.IntegerField(default=0)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Game')),
                ('hh_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.HH_Player')),
            ],
        ),
        migrations.CreateModel(
            name='HHJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=mhc.storage_backend.PrivateJsonStorage(), upload_to='')),
                ('hh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.HH')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='hh_player',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Player'),
        ),
    ]
