# Generated by Django 2.0 on 2018-01-03 04:58

from django.db import migrations, models
import mhc.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhjson',
            name='file',
            field=models.FileField(storage=mhc.storage_backend.PrivateUnconvertedStorage(), upload_to=''),
        ),
    ]
