# Generated by Django 2.0 on 2018-01-08 22:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hh',
            managers=[
                ('active_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
