# Generated by Django 2.0 on 2018-01-03 04:59

from django.db import migrations, models
import mhc.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0002_auto_20180103_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhjson',
            name='file',
            field=models.FileField(storage=mhc.storage_backend.PrivateJsonStorage(), upload_to=''),
        ),
    ]
