# Generated by Django 2.0 on 2018-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0002_hh2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hh2',
            name='file',
        ),
        migrations.AddField(
            model_name='hh2',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hh2',
            name='file_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hh2',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hh2',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hh2',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hh2',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
