# Generated by Django 2.0 on 2018-01-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0002_auto_20180108_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.CharField(max_length=31)),
                ('date_played', models.CharField(max_length=31)),
                ('time_played', models.CharField(max_length=31)),
                ('sb', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bb', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ante', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('table', models.CharField(max_length=63)),
                ('blind_type', models.CharField(max_length=63)),
                ('rake', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pot', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sitting', models.IntegerField(default=0)),
                ('dealt', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Game')),
                ('hh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.HH')),
            ],
        ),
        migrations.CreateModel(
            name='Hand_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sitting', models.BooleanField()),
                ('hand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Hand')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Player')),
            ],
        ),
    ]
