# Generated by Django 2.0 on 2018-01-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0004_hand_hand_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maniahandconverter.Game'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='ante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='bb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='pot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='rake',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='sb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
