# Generated by Django 2.0 on 2018-01-10 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0004_auto_20180109_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhnew',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
