# Generated by Django 2.0 on 2018-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maniahandconverter', '0005_hhnew_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh',
            name='path',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
